/**
 * Design direction: Technical Drop Editorial — the story page reads like a sparse campaign manifesto, not a conventional corporate history.
 */
import { ArrowRight, Check } from "lucide-react";
import { Link } from "wouter";

const principles = [
  { number: "01", title: "Feel the grip", text: "Every visual move starts where the rider meets the bike: touch, pressure, repeat." },
  { number: "02", title: "Keep the signal", text: "Color earns its place. One sharp choice will always outwork a noisy palette." },
  { number: "03", title: "Lose the excess", text: "If it does not change the ride or the read, it does not need to be there." },
];

export default function About() {
  return (
    <>
      <section className="relative min-h-[690px] overflow-hidden bg-[#111214] pt-[68px]"><img src="/manus-storage/underrated-cockpit_6568441b.jpg" alt="Close-up of a graphite bike cockpit" className="absolute inset-0 h-full w-full object-cover object-[70%_center] opacity-75" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(7,8,8,.96)_0%,rgba(7,8,8,.83)_42%,rgba(7,8,8,.2)_100%)]" /><div className="relative mx-auto flex min-h-[622px] max-w-[1440px] flex-col justify-end px-4 pb-12 sm:px-6 lg:px-9 lg:pb-16"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#ff5a36]">The point of view</p><h1 className="mt-5 max-w-3xl font-display text-[clamp(5rem,10vw,10rem)] uppercase leading-[.67] tracking-[-.065em] text-white">Nothing<br />is <em className="text-[#ff5a36]">minor.</em></h1><p className="mt-7 max-w-md text-base leading-7 text-white/60">Every piece on a bike does a job. We just think it deserves to look like it knows exactly what that job is.</p></div></section>
      <section className="bg-[#eae6df] px-4 py-16 text-[#0c0d0e] sm:px-6 lg:px-9 lg:py-24"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#ff5a36]">Built different</p><h2 className="mt-5 font-display text-7xl uppercase leading-[.7] tracking-[-.055em] sm:text-8xl">The build<br />is the <em>brief.</em></h2></div><div className="max-w-2xl lg:pt-12"><p className="text-xl leading-8 text-black/75">Underrated Cycling Co. exists for the point where function, personality, and attention overlap. We make small visual decisions feel worth making—because riders notice.</p><p className="mt-6 text-sm leading-7 text-black/60">Deep shadows, hard crop lines, and a flare of color put each component in focus. This is a product world made for riders who care where every part lands.</p><Link href="/shop" className="mt-8 inline-flex items-center gap-2 border border-black px-4 py-3 text-[10px] font-bold uppercase tracking-[.15em] transition hover:border-[#ff5a36] hover:bg-[#ff5a36]">Find your detail <ArrowRight size={14} /></Link></div></div></section>
      <section className="bg-[#0c0d0e] px-4 py-16 sm:px-6 lg:px-9 lg:py-24"><div className="mx-auto max-w-[1440px]"><div className="border-b border-white/15 pb-7"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#ff5a36]">Three rules</p><h2 className="mt-4 font-display text-6xl uppercase leading-[.74] tracking-[-.05em] text-white sm:text-7xl">The <em>filter.</em></h2></div><div className="grid border-l border-white/15 sm:grid-cols-3">{principles.map((principle) => <article key={principle.number} className="border-b border-r border-white/15 p-5 py-10 sm:min-h-80"><p className="text-[10px] font-bold tracking-[.16em] text-[#ff5a36]">{principle.number}</p><h3 className="mt-12 font-display text-4xl uppercase leading-[.82] text-white">{principle.title}</h3><p className="mt-5 max-w-xs text-sm leading-6 text-white/45">{principle.text}</p></article>)}</div></div></section>
      <section className="bg-[#111214] px-4 py-16 sm:px-6 lg:px-9"><div className="mx-auto grid max-w-[1440px] gap-8 lg:grid-cols-2"><div className="border border-white/15 p-6 sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[.17em] text-[#ff5a36]">Design notes</p><p className="mt-7 font-display text-5xl uppercase leading-[.75] text-white">The details<br />are the <em>difference.</em></p><div className="mt-9 space-y-3">{["Dark, hard-lit product presentation", "Tangerine only where attention matters", "Fast, visible response to every action"].map((item) => <p key={item} className="flex gap-3 border-t border-white/10 pt-3 text-sm text-white/55"><Check size={16} className="shrink-0 text-[#ff5a36]" />{item}</p>)}</div></div><div className="relative min-h-[330px] overflow-hidden bg-[#151719]"><img src="/manus-storage/underrated-reference-grid-2_92e5ffa0.png" alt="Underrated Cycling product grid reference" className="absolute inset-0 h-full w-full object-cover object-center" /><div className="absolute inset-0 bg-gradient-to-t from-black/85 via-transparent to-transparent" /><p className="absolute bottom-6 left-6 font-display text-5xl uppercase leading-[.76] text-white">The<br /><em className="text-[#ff5a36]">source.</em></p></div></div></section>
    </>
  );
}
